roles:
  # Install a tailscale role from the Ansible Galaxy
  - src: artis3n.tailscale
  # Install rclone role from Ansible Galaxy
  - src: stefangweichinger.ansible_rclone
  # Install and setup duplicati
  - src: hwwilliams.duplicati
  # Install Caddy
  - src: caddy_ansible.caddy_ansible