control_node:
  hosts:
    localhost:
      ansible_connection: local

servers:
  hosts:
    server01:
      ansible_host: 192.168.86.101
      primary_user: pi
      docker_compose_dirs: ["/opt/server/", "/opt/media_server/"]
      backup_dirs: ["/opt"]
      samba_shares: [{"name":"home", "path":"/home/pi", "comment":"pi home folder"}, {"name":"opt", "path":"/opt", "comment":"opt directory", "root":true}, {"name":"storage", "path":"/mnt/storage", "comment":"storage drives"}]
    
    server02:
      ansible_host: 192.168.86.102
      primary_user: pi
      docker_compose_dirs: ["/opt/server/"]
      backup_dirs: ["/opt"]
      samba_shares: [{"name":"home", "path":"/home/pi", "comment":"pi home folder"}, {"name":"opt", "path":"/opt", "comment":"opt directory", "root":true}]

    server04:
      ansible_host: 192.168.86.104
      primary_user: patrick
      docker_compose_dirs: ["/opt/server/"]
      backup_dirs: ["/opt", "/home/patrick/homelab-ansible"]
      samba_shares: [{"name":"home", "path":"/home/patrick", "comment":"patrick home folder"}, {"name":"opt", "path":"/opt", "comment":"opt directory", "root":true}]

    server05:
      ansible_host: 192.168.86.105
      primary_user: patrick
      docker_compose_dirs: ["/opt/server/"]
      backup_dirs: ["/opt"]
      samba_shares: [{"name":"home", "path":"/home/patrick", "comment":"patrick home folder"}, {"name":"opt", "path":"/opt", "comment":"opt directory", "root":true}]
    
    server-dev:
      ansible_host: 192.168.86.110
      primary_user: patrick
      docker_compose_dirs: []
      backup_dirs: ["/home"]
      samba_shares: [{"name":"home", "path":"/home/patrick", "comment":"patrick home folder"}, {"name":"opt", "path":"/opt", "comment":"opt directory", "root":true}]
    
    starlord:
      ansible_host: starlord
      primary_user: root
    
    fury:
      ansible_host: fury
      primary_user: patrick
      backup_dirs: ["/home/patrick"]
      samba_shares: [{"name":"root", "path":"/root", "comment":"root folder"}, {"name":"patrick", "path":"/home/patrick", "comment":"patrick home folder"}]
      pve_host: starlord
      pve_id: 106
    
    nas:
      ansible_host: nas
      primary_user: root
      backup_dirs: ["/root"]
      nfs_dir: "/mnt/storage"
      samba_shares: [{"name":"root", "path":"/root", "comment":"root folder"},{"name":"storage", "path":"/mnt/storage-test", "comment":"storage drives"}]
      pve_host: starlord
      pve_id: 107
      
    pbs:
      ansible_host: 192.168.86.108
      primary_user: patrick
      backup_dirs: ["/home/patrick"]
      samba_shares: [{"name":"patrick", "path":"/home/patrick", "comment":"patrick home folder"}]
      pve_host: starlord
      pve_id: 108

    
automation:
  hosts:
    homeassistant:
      ansible_host: 192.168.86.100
      ansible_user: root

ssh_share:
  hosts:
    server01:
    pve-starlord:
    pve-fury:
    pve-nas:
    homeassistant:
    # server02:
    # server04:
    # server05:
    # server-dev:

temporary:    
  hosts:
    temp:
      ansible_host: 192.168.86.109
      ansible_user: root
      pve_id: 200
      # samba_shares: [{"name":"root", "path":"/root", "comment":"root folder"}]