control_node:
  hosts:
    localhost:
      ansible_user: patrick
      ansible_connection: local

servers:
  hosts:
    server01:
      ansible_host: 192.168.86.101
      ansible_user: pi
      docker_compose_dirs: ["/opt/server/", "/opt/plex/"]
    server02:
      ansible_host: 192.168.86.102
      ansible_user: pi
      docker_compose_dirs: ["/opt/server_secondary/"]
    new_server01:
      ansible_host: 192.168.86.181
      ansible_user: pi
      ansible_host_key_checking: false
      docker_compose_dirs: ["/opt/server/", "/opt/plex/"]
    new_server02:
      ansible_host: 192.168.86.29
      ansible_user: pi
      docker_compose_dirs: ["/opt/server/"]

automation:
  hosts:
    homeassistant:
      ansible_host: 192.168.86.100
      ansible_user: root

ssh_share:
  hosts:
    server01:
    server02:
    homeassistant:
    new_server01:
    new_server02: