servers:
  hosts:
    server01:
      ansible_host: 192.168.86.101
      ansible_user: pi
      docker_compose_dirs: ["/opt/server/", "/opt/plex/"]
    server02:
      ansible_host: 192.168.86.102
      ansible_user: pi
      docker_compose_dirs: ["/opt/server_secondary/"]

control_node:
  hosts:
    localhost:
      ansible_host: 
      ansible_user: patrick
      ansible_connection: local
        