control_node:
  hosts:
    localhost:
      ansible_user: patrick
      ansible_connection: local

servers:
  hosts:
    server01:
      ansible_host: 192.168.86.101
      ansible_user: pi
      docker_compose_dirs: ["/opt/server/", "/opt/plex/"]
      backup_dirs: ["/opt"]
      samba_shares: [{"name":"home", "path":"/home/pi", "comment":"pi home folder"}, {"name":"opt", "path":"/opt", "comment":"opt directory", "root":true}, {"name":"external", "path":"/mnt/external", "comment":"external storage"}]
    server02:
      ansible_host: 192.168.86.102
      ansible_user: pi
      docker_compose_dirs: ["/opt/server/"]
      backup_dirs: ["/opt"]
      samba_shares: [{"name":"home", "path":"/home/pi", "comment":"pi home folder"}, {"name":"opt", "path":"/opt", "comment":"opt directory", "root":true}]

    server04:
      ansible_host: 192.168.86.104
      ansible_user: patrick
      docker_compose_dirs: ["/opt/server/"]
      backup_dirs: ["/opt", "/home/patrick"]
      samba_shares: [{"name":"home", "path":"/home/patrick", "comment":"patrick home folder"}, {"name":"opt", "path":"/opt", "comment":"opt directory", "root":true}]

automation:
  hosts:
    homeassistant:
      ansible_host: 192.168.86.100
      ansible_user: root

ssh_share:
  hosts:
    server01:
    server02:
    server04:
    homeassistant:

# temp:    
  # hosts:
    # new_control_node:
      # ansible_host: 192.168.86.104
      # ansible_user: patrick