control_node:
  hosts:
    localhost:
      ansible_user: patrick
      ansible_connection: local

servers:
  hosts:
    server01:
      ansible_host: 192.168.86.101
      ansible_user: pi
      docker_compose_dirs: ["/opt/server/", "/opt/plex/"]
    server02:
      ansible_host: 192.168.86.102
      ansible_user: pi
      docker_compose_dirs: ["/opt/server/"]

automation:
  hosts:
    homeassistant:
      ansible_host: 192.168.86.100
      ansible_user: root

ssh_share:
  hosts:
    server01:
    server02:
    homeassistant:

temp:    
  hosts:
    new_control_node:
      ansible_host: 192.168.86.104
      ansible_user: patrick