control_node:
  hosts:
    localhost:
      ansible_connection: local

servers:
  hosts:
    server04:
      ansible_host: 192.168.86.104
      primary_user: patrick
      docker_compose_dirs: ["/opt/server/"]
      backup_dirs: ["/opt"]
      samba_shares: [{"name":"home", "path":"/home/patrick", "comment":"patrick home folder"}, {"name":"opt", "path":"/opt", "comment":"opt directory", "root":true}]
    
    starlord:
      ansible_host: 192.168.86.105
      primary_user: root
    
    stark:
      ansible_host: 192.168.86.103
      primary_user: root
    
    fury:
      ansible_host: 192.168.86.106
      primary_user: patrick
      samba_shares: [{"name":"patrick", "path":"/home/patrick", "comment":"patrick home folder"}, {"name":"opt", "path":"/opt", "comment":"opt directory", "root":true}]
      pve_host: stark
      pve_id: 106
      
    pbs:
      ansible_host: 192.168.86.112
      primary_user: patrick
      samba_shares: [{"name":"patrick", "path":"/home/patrick", "comment":"patrick home folder"}, {"name":"opt", "path":"/opt", "comment":"opt directory", "root":true}]
    
    omv:
      ansible_host: 192.168.86.109
      primary_user: patrick
      samba_shares: []
      pve_host: starlord
      pve_id: 109
    
    bifrost:
      ansible_host: 192.168.86.111
      primary_user: patrick
      docker_compose_dirs: ["/opt/server/"]
      samba_shares: [{"name":"patrick", "path":"/home/patrick", "comment":"patrick home folder"}, {"name":"opt", "path":"/opt", "comment":"opt directory", "root":true}]
      pve_host: starlord
      pve_id: 102
    
    plex:
      ansible_host: 192.168.86.107
      primary_user: root
      pve_host: starlord
      pve_id: 107
      
    jellyfin:
      ansible_host: 192.168.86.108
      primary_user: root
      pve_host: starlord
      pve_id: 108
      
    yondu:
      ansible_host: 192.168.86.114
      primary_user: patrick
      samba_shares: [{"name":"patrick", "path":"/home/patrick", "comment":"patrick home folder"}, {"name":"opt", "path":"/opt", "comment":"opt directory", "root":true}]
      pve_host: starlord
      pve_id: 114
    
    frigate:
      ansible_host: 192.168.86.116
      primary_user: root
      samba_shares: [{"name":"root", "path":"/root", "comment":"root folder"}, {"name":"opt", "path":"/opt", "comment":"opt directory", "root":true}]
      pve_host: starlord
      pve_id: 116
    
automation:
  hosts:
    homeassistant:
      ansible_host: 192.168.86.100
      ansible_user: root
      primary_user: root

ssh_share:
  hosts:
    server04:
    starlord:
    stark:
    pbs:
    fury:
    omv:
    yondu:
