servers:
  hosts:
    server01:
      ansible_host: 192.168.86.101
      ansible_user: pi
    server02:
      ansible_host: 192.168.86.102
      ansible_user: pi

control_node:
  hosts:
    localhost:
      ansible_host: 
      ansible_user: patrick
        