control_node:
  hosts:
    localhost:
      ansible_user: patrick
      ansible_connection: local

servers:
  hosts:
    server01:
      ansible_host: 192.168.86.101
      ansible_user: pi
      docker_compose_dirs: ["/opt/server/", "/opt/media_server/"]
      backup_dirs: ["/opt"]
      samba_shares: [{"name":"home", "path":"/home/pi", "comment":"pi home folder"}, {"name":"opt", "path":"/opt", "comment":"opt directory", "root":true}, {"name":"storage", "path":"/mnt/storage", "comment":"storage drives"}]
    
    server02:
      ansible_host: 192.168.86.102
      ansible_user: pi
      docker_compose_dirs: ["/opt/server/"]
      backup_dirs: ["/opt"]
      #backup_dirs: ["/opt"]
      samba_shares: [{"name":"home", "path":"/home/pi", "comment":"pi home folder"}, {"name":"opt", "path":"/opt", "comment":"opt directory", "root":true}]

    server04:
      ansible_host: 192.168.86.104
      ansible_user: patrick
      docker_compose_dirs: ["/opt/server/"]
      backup_dirs: ["/opt", "/home/patrick/homelab-ansible"]
      samba_shares: [{"name":"home", "path":"/home/patrick", "comment":"patrick home folder"}, {"name":"opt", "path":"/opt", "comment":"opt directory", "root":true}]

    server05:
      ansible_host: 192.168.86.105
      ansible_user: patrick
      docker_compose_dirs: ["/opt/server/"]
      backup_dirs: ["/opt"]
      samba_shares: [{"name":"home", "path":"/home/patrick", "comment":"patrick home folder"}, {"name":"opt", "path":"/opt", "comment":"opt directory", "root":true}]
    
    server-dev:
      ansible_host: 192.168.86.110
      ansible_user: patrick
      docker_compose_dirs: []
      backup_dirs: ["/home"]
      samba_shares: [{"name":"home", "path":"/home/patrick", "comment":"patrick home folder"}, {"name":"opt", "path":"/opt", "comment":"opt directory", "root":true}]
    
    pve-ansible:
      ansible_host: 192.168.86.106
      ansible_user: root
      backup_dirs: ["/root"]
      samba_shares: [{"name":"root", "path":"/root", "comment":"root folder"}]
    
automation:
  hosts:
    homeassistant:
      ansible_host: 192.168.86.100
      ansible_user: root

ssh_share:
  hosts:
    server01:
    server02:
    server04:
    server05:
    homeassistant:
    server-dev:

temp:    
  hosts:
    new_control_node:
      ansible_host: 192.168.86.106
      ansible_user: root
      samba_shares: [{"name":"root", "path":"/root", "comment":"root folder"}]