control_node:
  hosts:
    localhost:
      ansible_connection: local

servers:
  hosts:
    starlord:
      ansible_host: starlord
      ip: 192.168.86.95
      primary_user: root
    
    stark:
      ansible_host: 192.168.86.93
      ip: 192.168.86.93
      primary_user: root
    
    fury:
      ansible_host: fury
      ip: 192.168.86.106
      primary_user: patrick
      samba_shares: [{"name":"patrick", "path":"/home/patrick", "comment":"patrick home folder"}, {"name":"opt", "path":"/opt", "comment":"opt directory", "root":true}]
      docker_compose_dirs: ["/opt/docker"]
      pve_host: stark
      pve_id: 106
        
    pbs:
      ansible_host: 192.168.86.98
      ip: 192.168.86.98
      primary_user: root
      backup_dirs: []
      samba_shares: []
    
    pihole1:
      ansible_host: 192.168.86.101
      primary_user: root
      backup_dirs: []
      samba_shares: []
      pve_host: stark
      pve_id: 101
    
    pihole2:
      ansible_host: 192.168.86.102
      primary_user: root
      backup_dirs: []
      samba_shares: []
      pve_host: starlord
      pve_id: 102

    nextcloud:
      ansible_host: 192.168.86.104
      ip: 192.168.86.104
      primary_user: root
      samba_shares: [{"name":"opt", "path":"/opt", "comment":"opt directory", "root":true}]
      pve_host: stark
      pve_id: 104

    plex:
      ansible_host: 192.168.86.107
      ip: 192.168.86.107
      primary_user: root
      pve_host: starlord
      pve_id: 107
      
    jellyfin:
      ansible_host: 192.168.86.108
      ip: 192.168.86.108
      primary_user: root
      pve_host: starlord
      pve_id: 108
      
    yondu:
      ansible_host: 192.168.86.114
      ip: 192.168.86.114
      primary_user: patrick
      samba_shares: [{"name":"patrick", "path":"/home/patrick", "comment":"patrick home folder"}, {"name":"opt", "path":"/opt", "comment":"opt directory", "root":true}]
      docker_compose_dirs: ["/opt/media_server"]
      pve_host: starlord
      pve_id: 114
    
    frigate:
      ansible_host: 192.168.86.116
      ip: 192.168.86.116
      primary_user: root
      samba_shares: [{"name":"root", "path":"/root", "comment":"root folder"}, {"name":"opt", "path":"/opt", "comment":"opt directory", "root":true}]
      docker_compose_dirs: ["/opt/server"]
      pve_host: starlord
      pve_id: 116
    
    immich:
      ansible_host: 192.168.86.115
      ip: 192.168.86.115
      primary_user: root
      samba_shares: [{"name":"root", "path":"/root", "comment":"root folder"}, {"name":"opt", "path":"/opt", "comment":"opt directory", "root":true}]
      docker_compose_dirs: ["/opt/server/immich"]
      pve_host: starlord
      pve_id: 115
    
    homarr:
      ansible_host: 192.168.86.112
      ip: 192.168.86.112
      primary_user: root
      samba_shares: [{"name":"root", "path":"/root", "comment":"root folder"}, {"name":"opt", "path":"/opt", "comment":"opt directory", "root":true}]
      docker_compose_dirs: ["/opt/docker"]
      pve_host: stark
      pve_id: 112
      
    caddy:
      ansible_host: 192.168.86.118
      ip: 192.168.86.118
      primary_user: root
      samba_shares: [{"name":"root", "path":"/root", "comment":"root folder"}, {"name":"caddy", "path":"/etc/caddy", "comment":"caddy folder"}]
      pve_host: stark
      pve_id: 118
    
    print-server:
      ansible_host: 192.168.86.214
      ip: 192.168.86.214
      primary_user: patrick
      samba_shares: [{"name":"patrick", "path":"/home/patrick", "comment":"patrick home folder"}, {"name":"opt", "path":"/opt", "comment":"opt directory", "root":true}]
    
    matrix:
      ansible_host: 192.168.86.120
      ip: 192.168.86.120
      primary_user: root
      samba_shares: [{"name":"root", "path":"/root", "comment":"root folder"}, {"name":"opt", "path":"/opt", "comment":"opt directory", "root":true}]
      docker_compose_dirs: ["/opt/docker"]
      pve_host: stark
      pve_id: 120
    
    audiobookshelf:
      ansible_host: 192.168.86.105
      ip: 192.168.86.105
      primary_user: root
      pve_host: starlord
      pve_id: 105
    
    ddclient:
      ansible_host: 192.168.86.103
      ip: 192.168.86.103
      primary_user: root
      samba_shares: [{"name":"root", "path":"/root", "comment":"root folder"}, {"name":"opt", "path":"/opt", "comment":"opt directory", "root":true}]
      pve_host: stark
      pve_id: 103
    
    uptimekuma:
      ansible_host: 192.168.86.117
      ip: 192.168.86.117
      primary_user: root
      pve_host: stark
      pve_id: 117

truenas_machines:
  hosts:
    truenas_home:
      ansible_host: truenas
      ip: 192.168.86.99
      primary_user: admin
      ansible_remote_tmp: /var/tmp/admin
    
    truenas_bucky:
      ansible_host: 100.124.132.103
      primary_user: admin
      ansible_remote_tmp: /var/tmp/admin

workstations:
  hosts:
    debian_vm:
      ansible_host: 192.168.86.232
      primary_user: patrick
      pve_host: stark
      pve_id: 109

network:
  hosts:  
    glinet-flint:
      ansible_host: 192.168.86.1
      ip: 192.168.86.1
      primary_user: root

    
automation:
  hosts:
    homeassistant:
      ansible_host: 192.168.86.100
      ansible_user: root
      primary_user: root

ssh_share:
  hosts:
    starlord:
    stark:
    pbs:
    fury:
    yondu:
    truenas:

tailscale:
  hosts:
    starlord:
    stark:
    pbs:
    fury:
    yondu:
    jellyfin:
    plex:
    duplicati:
    immich:
    nextcloud:
    frigate:
    ddclient:
    audiobookshelf:
    matrix:
    print-server:
    # heimdall:
    pihole1:
    pihole2:
    
    
