control_node:
  hosts:
    localhost:
      ansible_connection: local

servers:
  hosts:
    starlord:
      ansible_host: starlord
      ip: 192.168.86.95
      port: 8006
      primary_user: root
      local_proxy: {"https": true}

    stark:
      ansible_host: stark
      ip: 192.168.86.93
      port: 8006
      primary_user: root
      proxmox_notifications: true
      local_proxy: {"https": true}

    loki:
      ansible_host: loki
      ip: 192.168.86.97
      port: 8006
      primary_user: root
      local_proxy: {"https": true}
    
    cap:
      ansible_host: cap
      ip: 192.168.86.94
      port: 8006
      primary_user: root
      local_proxy: {"https": true}

    nix-fury:
      ansible_host: nix-fury
      ip: 192.168.86.106
      primary_user: patrick
      samba_shares: [{"name":"patrick", "path":"/home/patrick", "comment":"patrick home folder"}, {"name":"opt", "path":"/opt", "comment":"opt directory", "root":true}]
      # docker_compose_dirs: ["/opt/docker"]
      pve_host: loki
      pve_id: 106

    pbs:
      ansible_host: pbs
      ip: 192.168.86.98
      port: 8007
      primary_user: root
      backup_dirs: []
      samba_shares: []
      local_proxy: {"https": true}

    omada:
      ansible_host: omada
      ip: 192.168.86.111
      port: 8043
      primary_user: root
      pve_host: loki
      pve_id: 111
      local_proxy: {"https": true}

    opnsense:
      ansible_host: opnsense
      ip: 192.168.86.1
      port: 80
      primary_user: root
      pve_host: loki
      pve_id: 109
      local_proxy: {}
    
    nextcloud:
      ansible_host: nextcloud
      ip: 192.168.86.104
      port: 443
      primary_user: root
      pve_host: stark
      pve_id: 104
      reverse_proxy: {"subdomain":"nextcloud", "port":"443", "tls_insecure": true}

    jellyfin:
      ansible_host: jellyfin
      ip: 192.168.86.108
      port: 8096
      primary_user: root
      pve_host: starlord
      pve_id: 108
      reverse_proxy: {"subdomain":"jellyfin", "port":"8096"}

    yondu:
      ansible_host: yondu
      ip: 192.168.86.114
      primary_user: patrick
      samba_shares: [{"name":"patrick", "path":"/home/patrick", "comment":"patrick home folder"}, {"name":"opt", "path":"/opt", "comment":"opt directory", "root":true}]
      docker_compose_dirs: ["/opt/stacks/media_server"]
      pve_host: starlord
      pve_id: 114
      local_proxy:
        - {"subdomain":"qbittorrent", "port":"8080"}
        - {"subdomain":"radarr", "port":"7878"}
        - {"subdomain":"sonarr", "port":"8989"}
        - {"subdomain":"readarr", "port":"8787"}
        - {"subdomain":"bazarr", "port":"6767"}
        - {"subdomain":"prowlarr", "port":"9696"}

    frigate:
      ansible_host: frigate
      ip: 192.168.86.116
      port: 5000
      primary_user: root
      samba_shares: [{"name":"root", "path":"/root", "comment":"root folder"}, {"name":"opt", "path":"/opt", "comment":"opt directory", "root":true}]
      docker_compose_dirs: ["/opt/server"]
      pve_host: stark
      pve_id: 116
      local_proxy: {}

    immich:
      ansible_host: immich
      ip: 192.168.86.115
      port: 2283
      primary_user: root
      samba_shares: [{"name":"root", "path":"/root", "comment":"root folder"}, {"name":"opt", "path":"/opt", "comment":"opt directory", "root":true}]
      docker_compose_dirs: ["/opt/server/immich"]
      pve_host: starlord
      pve_id: 115
      reverse_proxy: {"subdomain":"immich", "port":"2283"}

    print-server:
      ansible_host: print-server
      ip: 192.168.86.214
      primary_user: patrick
      samba_shares: [{"name":"patrick", "path":"/home/patrick", "comment":"patrick home folder"}, {"name":"opt", "path":"/opt", "comment":"opt directory", "root":true}]

    audiobookshelf:
      ansible_host: audiobookshelf
      ip: 192.168.86.105
      port: 13378
      primary_user: root
      pve_host: starlord
      pve_id: 105
      reverse_proxy: {"subdomain":"audiobooks", "port":"13378"}

    uptimekuma:
      ansible_host: uptimekuma
      ip: 192.168.86.117
      port: 3001
      primary_user: root
      pve_host: cap
      pve_id: 117
      local_proxy: {}

    dockge:
      ansible_host: dockge
      ip: 192.168.86.112
      port: 5001
      primary_user: root
      pve_host: cap
      pve_id: 112
      local_proxy: {}

    homepage:
      ansible_host: homepage
      ip: 192.168.86.121
      port: 3000
      primary_user: root
      pve_host: stark
      pve_id: 121
      local_proxy: {}

    forgejo:
      ansible_host: forgejo
      ip: 192.168.86.120
      port: 3000
      primary_user: root
      pve_host: cap
      pve_id: 120
      local_proxy: {"subdomain": "git"}
    
    gotify:
      ansible_host: gotify
      ip: 192.168.86.122
      primary_user: root
      pve_host: stark
      pve_id: 122
      reverse_proxy: {"subdomain":"gotify", "port":"80"}
    
    linkwarden:
      ansible_host: linkwarden
      ip: 192.168.86.123
      port: 3000
      primary_user: root
      pve_host: stark
      pve_id: 123
      reverse_proxy: {"subdomain":"linkwarden", "port":"3000"}
        
    myspeed:
      ansible_host: 192.168.86.125
      ip: 192.168.86.125
      port: 5216
      primary_user: root
      pve_host: loki
      pve_id: 125
      local_proxy: {}
    
    paperless-ngx:
      ansible_host: paperless-ngx
      ip: 192.168.86.126
      port: 8000
      primary_user: root
      pve_host: stark
      pve_id: 126
      local_proxy: {}
    
    mealie:
      ansible_host: mealie
      ip: 192.168.86.107
      port: 9925
      primary_user: root
      docker_compose_dirs: ["/opt/docker"]
      pve_host: stark
      pve_id: 107
      reverse_proxy: {"subdomain":"mealie", "port":"9925"}
    
    bitcoin:
      ansible_host: bitcoin
      ip: 192.168.86.103
      port: 8080
      primary_user: root
      docker_compose_dirs: ["/opt/docker"]
      pve_host: loki
      pve_id: 103
      # reverse_proxy: {"subdomain":"bitcoin", "port":"8080"}

    caddy-local:
      ansible_host: caddy-local
      ip: 192.168.86.118
      primary_user: root
      pve_host: loki
      pve_id: 118

    do-caddy:
      ansible_host: do-caddy
      #ip: 
      primary_user: root

    rn-pangolin:
      ansible_host: rn-pangolin
      primary_user: patrick
    
    truenas:
      ansible_host: truenas
      ip: 192.168.86.99
      primary_user: admin
      ansible_remote_tmp: /var/tmp/admin
      local_proxy:
        - {"https": true}
        - {"subdomain":"syncthing", "port":"20910"}

    wakanda:
      ansible_host: wakanda
      primary_user: root
      proxmox_notifications: true
      tailscale_routes: "10.10.12.0/24"

    bucky:
      ansible_host: bucky
      #ip: 100.124.132.103
      primary_user: admin
      ansible_remote_tmp: /var/tmp/admin

cluster_nodes:
  hosts:
    starlord:
    stark:
    loki:
    cap:
    wakanda:

local_cluster_nodes:
  hosts:
    starlord:
    stark:
    loki:
    cap:

truenas_machines:
  hosts:
    truenas_home:
    truenas_bucky:
    

workstations:
  hosts:
    debian_vm:
      ansible_host: 192.168.86.232
      primary_user: patrick
      pve_host: stark
      pve_id: 109


automation:
  hosts:
    homeassistant:
      ansible_host: homeassistant
      ip: 192.168.86.100
      port: 8123
      ansible_user: root
      primary_user: root

ssh_share:
  hosts:
    starlord:
    stark:
    pbs:
    fury:
    yondu:
    truenas:

tailscale:
  hosts:
    starlord:
    stark:
    pbs:
    fury:
    yondu:
    jellyfin:
    plex:
    immich:
    nextcloud:
    frigate:
    ddclient:
    audiobookshelf:
    print-server:
    pihole1:
    pihole2:
