control_node:
  hosts:
    localhost:
      ansible_connection: local

servers:
  hosts:
    starlord:
      ansible_host: starlord
      ip: 192.168.86.95
      primary_user: root

    stark:
      ansible_host: stark
      ip: 192.168.86.93
      primary_user: root
      local_fqdn_port: 8006

    loki:
      ansible_host: loki
      ip: 192.168.86.97
      primary_user: root

    fury:
      ansible_host: fury
      ip: 192.168.86.106
      primary_user: patrick
      samba_shares: [{"name":"patrick", "path":"/home/patrick", "comment":"patrick home folder"}, {"name":"opt", "path":"/opt", "comment":"opt directory", "root":true}]
      docker_compose_dirs: ["/opt/docker"]
      pve_host: loki
      pve_id: 106

    pbs:
      ansible_host: pbs
      ip: 192.168.86.98
      primary_user: root
      backup_dirs: []
      samba_shares: []

    pihole1:
      ansible_host: pihole1
      ip: 192.168.86.101
      primary_user: root
      backup_dirs: []
      samba_shares: []
      pve_host: loki
      pve_id: 101

    pihole2:
      ansible_host: pihole2
      ip: 192.168.86.102
      primary_user: root
      backup_dirs: []
      samba_shares: []
      pve_host: stark
      pve_id: 102

    nextcloud:
      ansible_host: nextcloud
      ip: 192.168.86.104
      primary_user: root
      samba_shares: [{"name":"opt", "path":"/opt", "comment":"opt directory", "root":true}]
      pve_host: stark
      pve_id: 104

    plex:
      ansible_host: plex
      ip: 192.168.86.107
      primary_user: root
      pve_host: starlord
      pve_id: 107

    jellyfin:
      ansible_host: jellyfin
      ip: 192.168.86.108
      primary_user: root
      pve_host: starlord
      pve_id: 108
      reverse_proxy: {"subdomain":"jellyfin", "port":"8096"}

    yondu:
      ansible_host: yondu
      ip: 192.168.86.114
      primary_user: patrick
      samba_shares: [{"name":"patrick", "path":"/home/patrick", "comment":"patrick home folder"}, {"name":"opt", "path":"/opt", "comment":"opt directory", "root":true}]
      docker_compose_dirs: ["/opt/media_server"]
      pve_host: starlord
      pve_id: 114

    frigate:
      ansible_host: frigate
      ip: 192.168.86.116
      primary_user: root
      samba_shares: [{"name":"root", "path":"/root", "comment":"root folder"}, {"name":"opt", "path":"/opt", "comment":"opt directory", "root":true}]
      docker_compose_dirs: ["/opt/server"]
      pve_host: starlord
      pve_id: 116
      local_fqdn_port: 5000

    immich:
      ansible_host: immich
      ip: 192.168.86.115
      primary_user: root
      samba_shares: [{"name":"root", "path":"/root", "comment":"root folder"}, {"name":"opt", "path":"/opt", "comment":"opt directory", "root":true}]
      docker_compose_dirs: ["/opt/server/immich"]
      pve_host: starlord
      pve_id: 115

    homarr:
      ansible_host: homarr
      ip: 192.168.86.112
      primary_user: root
      samba_shares: [{"name":"root", "path":"/root", "comment":"root folder"}, {"name":"opt", "path":"/opt", "comment":"opt directory", "root":true}]
      docker_compose_dirs: ["/opt/docker"]
      pve_host: stark
      pve_id: 112

    print-server:
      ansible_host: print-server
      ip: 192.168.86.214
      primary_user: patrick
      samba_shares: [{"name":"patrick", "path":"/home/patrick", "comment":"patrick home folder"}, {"name":"opt", "path":"/opt", "comment":"opt directory", "root":true}]

    audiobookshelf:
      ansible_host: audiobookshelf
      ip: 192.168.86.105
      primary_user: root
      pve_host: starlord
      pve_id: 105
      reverse_proxy: {"subdomain":"audiobooks", "port":"13378"}

    ddclient:
      ansible_host: ddclient
      ip: 192.168.86.103
      primary_user: root
      samba_shares: [{"name":"root", "path":"/root", "comment":"root folder"}, {"name":"opt", "path":"/opt", "comment":"opt directory", "root":true}]
      pve_host: stark
      pve_id: 103

    uptimekuma:
      ansible_host: uptimekuma
      ip: 192.168.86.117
      primary_user: root
      pve_host: stark
      pve_id: 117

    local-caddy:
      ansible_host: local-caddy
      ip: 192.168.86.118
      primary_user: root
      pve_host: loki
      pve_id: 118

    do-caddy:
      ansible_host: do-caddy
      #ip: 
      primary_user: root
    
    truenas_home:
      ansible_host: truenas
      ip: 192.168.86.99
      primary_user: admin
      ansible_remote_tmp: /var/tmp/admin

    truenas_bucky:
      ansible_host: bucky
      #ip: 100.124.132.103
      primary_user: admin
      ansible_remote_tmp: /var/tmp/admin

cluster_nodes:
  hosts:
    starlord:
    stark:
    loki:

truenas_machines:
  hosts:
    truenas_home:
    truenas_bucky:
    

workstations:
  hosts:
    debian_vm:
      ansible_host: 192.168.86.232
      primary_user: patrick
      pve_host: stark
      pve_id: 109


automation:
  hosts:
    homeassistant:
      ansible_host: homeassistant
      ip: 192.168.86.100
      ansible_user: root
      primary_user: root

ssh_share:
  hosts:
    starlord:
    stark:
    pbs:
    fury:
    yondu:
    truenas:

tailscale:
  hosts:
    starlord:
    stark:
    pbs:
    fury:
    yondu:
    jellyfin:
    plex:
    immich:
    nextcloud:
    frigate:
    ddclient:
    audiobookshelf:
    print-server:
    pihole1:
    pihole2:
