- name: Ensure group "docker" exists
  ansible.builtin.group:
    name: docker
    state: present

- name: add ansible user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: add primary user to docker group
  user:
    name: "{{ primary_user }}"
    groups: docker
    append: yes