- name: update pihole dns custom list
  template:
    src: "pihole_custom.list.j2"
    dest: /etc/pihole/custom.list
    owner: pihole
    group: pihole
    mode: 0644
  delegate_to: pihole1
  run_once: true