- name: Include Homelab Vars
  include_vars: vars/homelab_vars.yml
- name: Include Homelab Secret Vars
  include_vars: vars/homelab_secret_vars.yml

- name: INSTALL CONFIGURE EXTERNAL CADDY
  include_tasks: tasks/install_config_caddy.yml
  vars:
    caddy_file: "caddy/external_Caddyfile.j2"

- name: Ensure secure caddy directory exists
  ansible.builtin.file:
    path: /etc/caddy/secure
    state: directory

- name: Deploy secure caddy configuration
  ansible.builtin.template:
    src: templates/caddy/external_Caddyfile_secure.j2      # Path relative to your playbook's templates/ directory
    dest: /etc/caddy/secure/secure-services.caddy.disabled
