- name: remove old versions of docker
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
  become: true

- name: install docker dependencies
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - python3-pip
    state: present
    update_cache: true
  become: true

- name: add docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add docker repository to apt
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: install docker engine
  apt:
    name: 
      - docker-ce 
      - docker-ce-cli 
      - containerd.io
      - docker-compose-plugin
    state: present
    update_cache: true
  become: true

- name: check docker is active
  service:
    name: docker
    state: started
    enabled: yes

- name: add users to docker group
  include_tasks: tasks/add_users_to_docker_group.yml
    
# - name: install docker, docker-compose python packages
  # pip:
    # name:
      # - docker
      # - docker-compose