- name: Include Homelab Vars
  include_vars: vars/homelab_vars.yml
- name: Include Homelab Secret Vars
  include_vars: vars/homelab_secret_vars.yml
# - name: Include Caddy Vars
#   include_vars: vars/caddy.yml

- name: install and configure caddy
  include_role:
    name: caddy_ansible.caddy_ansible
  vars:
    caddy_config: "{{ lookup('template', '{{ caddy_file }}') }}"
    caddy_packages: ["github.com/caddy-dns/cloudflare"]
    caddy_systemd_capabilities_enabled: true

- name: install package tailscale-nginx-auth
  apt:
    name:
      - tailscale-nginx-auth
    state: present
  become: true

- name: Enable and start tailscale.nginx-auth.socket
  ansible.builtin.systemd:
    name: tailscale.nginx-auth.socket
    enabled: yes
    state: started

