- name: install packages - samba, git, restic, software-properties-common, fail2ban, unattended-upgrades, screen, rsync, sudo
  apt:
    name:
      - git
      - restic
      - software-properties-common
      - fail2ban
      - unattended-upgrades
      - screen
      - rsync
      - sudo
    state: latest
    update_cache: true
  become: true
  register: packages

- name: Start unattended-upgrades service, if not started
  ansible.builtin.service:
    name: unattended-upgrades
    state: started
  
- name: restic self-update
  ansible.builtin.shell:
    cmd: restic self-update
  changed_when: false
  
- name: install qemu-guest-agent
  apt:
    name:
      - qemu-guest-agent
    state: latest
    update_cache: true
  become: true
  when: ansible_virtualization_type == "kvm" and ansible_virtualization_role == "guest"
  register: qemu
  
- name: reboot host if qmeu-guest-agent is installed
  ansible.builtin.reboot:
  when: qemu.changed