- include_vars: vars/tailscale_vars.yml

### NEED TO ADD A CHECK TO SEE IF THE HOST IS AN LXC. ONLY NEED TO RUN ON AN LXC
- name: mount tun
  ansible.builtin.lineinfile:
    path: /etc/pve/lxc/{{ pve_id }}.conf
    regexp: '^lxc.mount.entry:'
    line: 'lxc.mount.entry: /dev/net/tun dev/net/tun none bind,create=file'
  delegate_to: pve-starlord
  register: config

- name: reboot machine to accept new config file
  ansible.builtin.reboot:
  when: config.changed

- name: Install and Setup Tailscale
  include_role:
    name: artis3n.tailscale