- name: Include Homelab Vars
  include_vars: vars/homelab_vars.yml
- name: Include Homelab Secret Vars
  include_vars: vars/homelab_secret_vars.yml

- name: INSTALL CONFIGURE EXTERNAL CADDY
  include_tasks: tasks/install_config_caddy.yml
  vars:
    caddy_file: "caddy/external_Caddyfile.j2"

- name: Ensure secure caddy directory exists
  ansible.builtin.file:
    path: /etc/caddy/secure
    state: directory

- name: Deploy secure caddy configuration
  ansible.builtin.template:
    src: templates/caddy/external_Caddyfile_secure.j2      # Path relative to your playbook's templates/ directory
    dest: /etc/caddy/secure/secure-services.caddy.disabled

- name: Copy enable-secure.sh file
  ansible.builtin.copy:
    src: templates/caddy/enable-secure.sh
    dest: /etc/caddy/secure/enable-secure.sh
    mode: '0770'

- name: Copy disable-secure.sh file
  ansible.builtin.copy:
    src: templates/caddy/disable-secure.sh
    dest: /etc/caddy/secure/disable-secure.sh
    mode: '0770'

- name: Copy status-secure.sh file
  ansible.builtin.copy:
    src: templates/caddy/status-secure.sh
    dest: /etc/caddy/secure/status-secure.sh
    mode: '0770'