- name: Include Homelab Vars
  include_vars: vars/homelab_vars.yml
- name: Include Homelab Secret Vars
  include_vars: vars/homelab_secret_vars.yml

- name: install nfs-common 
  apt:
    name: 
      - nfs-common
    state: present
    update_cache: true
  become: true

- name: make nextcloud directory
  file:
    path: /mnt/nextcloud
    state: directory

- name: Mount nextcloud NFS share on TrueNAS
  ansible.posix.mount:
    src: 192.168.86.99:/mnt/HDD-Mirror-01/nextcloud
    path: /mnt/nextcloud
    fstype: nfs
    opts: rw,sync,hard
    state: present
  become: true
  register: fstab
  
- name: mount all drives
  command: mount -a
  become: true
  when: fstab.changed