- name: add nas mountpoint
  ansible.builtin.lineinfile:
    path: /etc/pve/lxc/{{ pve_id }}.conf
    regexp: '^mp0:'
    line: 'mp0: /mnt/pve/nas,mp=/mnt/storage'
  delegate_to: pve-starlord
  vars:
    ansible_user: root
  register: config

- name: reboot machine to accept new config file
  ansible.builtin.reboot:
  when: config.changed