- name: Ensure lxc.apparmor.profile unconfined is in nas config file
  ansible.builtin.lineinfile:
    path: /etc/pve/lxc/{{pve_id}}.conf
    regexp: '^lxc.apparmor.profile:'
    line: 'lxc.apparmor.profile: unconfined'
  delegate_to: "{{ pve_host }}"
  vars:
    ansible_user: root
  register: config

- name: reboot machine to accept new config file
  ansible.builtin.reboot:
  when: config.changed