- name: Restore backed up directories to host
  ansible.posix.synchronize:
    src: "/mnt/external/backups/latest/{{ inventory_hostname }}/{{item.split('/') | last}}/"
    dest: "{{item}}/"
    delete: yes
  delegate_to: server01
  # become: true
  delegate_facts: true
  loop: "{{ backup_dirs }}"
  
# - name: show src
  # debug:
   # msg: "/mnt/external/backups/latest/{{ inventory_hostname }}/{{item.split('/') | last}}/"
  # loop: "{{ backup_dirs }}"
   
# - name: show dest
  # debug:
   # msg: "{{item}}/"
  # loop: "{{ backup_dirs }}"