- name: Restore opt folder to host
  ansible.posix.synchronize:
    src: "/mnt/external/backups/latest/{{ inventory_hostname }}/opt/"
    dest: /opt/
    delete: yes
  delegate_to: new_server01
  become: true
  delegate_facts: true