# Need to create a samba password on the server by running:
# $ sudo smbpasswd -a pi

- include_vars: vars/samba_vars.yml

- name: Configuring samba share
  template:
    src: "smb.conf.j2"
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: 0644
  register: samba_share
    
- name: Restart samba service
  ansible.builtin.service:
    name: smbd
    state: restarted
  when: samba_share.changed
    
- name: Create/update samba users
  include_tasks: "samba_users.yml"
  loop: "{{users}}"