# Need to create a samba password on the server by running:
# $ sudo smbpasswd -a pi

- name: Include Homelab Vars
  include_vars: vars/homelab_vars.yml
- name: Include Homelab Secret Vars
  include_vars: vars/homelab_secret_vars.yml

- name: install samba
  apt:
    name:
      - samba
      - samba-common-bin
    state: latest
    update_cache: true
  become: true

- name: Start samba service, if not started
  ansible.builtin.service:
    name: smbd
    state: started

- name: Configuring samba share
  template:
    src: "smb.conf.j2"
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: 0644
  register: samba_share
    
- name: Restart samba service
  ansible.builtin.service:
    name: smbd
    state: restarted
  when: samba_share.changed
    
- name: Create/update samba users
  include_tasks: "samba_users.yml"
  loop: "{{samba_users}}"