# - name: Check existence of smb user {{item.name}}
  # ansible.builtin.command: "pdbedit -u {{item.name}}"
  # register: userstat
  # failed_when: "userstat.rc not in [ 0, 256 ]"
  # changed_when: false

# - name: Create samba user {{item.name}}
  # shell: "(echo {{ item['smbpasswd'] }}; echo {{ item['smbpasswd'] }}) | smbpasswd -s -a {{ item['name'] }}"
  # when: userstat.rc == 256
  
- name: Configure Samba users.
  shell: >
    (pdbedit --user={{ item.name }} 2>&1 > /dev/null)
    || (echo '{{ item.smbpasswd }}'; echo '{{ item.smbpasswd }}')
    | smbpasswd -s -a {{ item.name }}

# - name: Enable samba user {{item.name}}
  # shell: "smbpasswd -e {{ item['name'] }}"
  # when: userstat.rc == 0