- name: Install rclone
  include_role:
    name: stefangweichinger.ansible_rclone
  vars:
    rclone_arch: "arm64"
    
- name: Copy rclone.conf file
  ansible.builtin.copy:
    src: proton_rclone_encrypted.conf
    dest: "/root/.config/rclone/rclone.conf"
    owner: root
    group: root
    mode: '0600'
    
- name: copy template backups.sh file
  template:
    src: "backups.sh.j2"
    dest: "/home/{{ primary_user }}/backup_script/backups.sh"
    owner: "{{ primary_user }}"
    group: "{{ primary_user }}"
    mode: 0777

- name: Ensure a job that runs backups.sh at 3:00 exists.
  ansible.builtin.cron:
    user: "{{ primary_user }}"
    name: "backups"
    minute: "0"
    hour: "3"
    job: "cd /home/{{ primary_user }}/backup_script && ./backups.sh"
  register: crontab

- name: Set Timezone
  include_tasks: "./tasks/set_timezone.yml"
  when: crontab.changed
