- name: Copy backup_script directory with owner and permissions
  ansible.builtin.copy:
    src: templates/backup_script
    dest: /home/pi
    owner: pi
    group: pi
    mode: '0777'

- name: Ensure a job that runs backups.sh at 23:59 exists.
  ansible.builtin.cron:
    user: pi
    name: "backups"
    minute: "58"
    hour: "23"
    job: "cd /home/pi/backup_script && ./backups.sh"
  register: crontab

- name: Set Timezone
  include_tasks: "./tasks/set_timezone.yml"
  when: crontab.changed
