- name: docker compose pull
  ansible.builtin.shell:
    cmd: docker compose pull
    chdir: "{{ item }}"
  loop: "{{ docker_compose_dirs }}"
    
- name: docker compose up -d --remove-orphans
  ansible.builtin.shell:
    cmd: docker compose up -d --remove-orphans
    chdir: "{{ item }}"
  loop: "{{ docker_compose_dirs }}"

- name: docker image prune
  ansible.builtin.shell:
    cmd: docker image prune -f