- name: docker compose pull, up, remove-orphans
  community.docker.docker_compose:
    project_src: "{{ item }}"
    pull: true
    remove_orphans: true
  become: true
  loop: "{{ docker_compose_dirs }}"
    
- name: docker image prune
  community.docker.docker_prune:
    images: true