# $ ansible-playbook playbooks/provision_print-server.yml

- name: PROVISION PRINT SERVER
  hosts: print-server
  become: yes
  
  pre_tasks:
    - name: UPDATE SYSTEM
      include_tasks: tasks/update_system.yml
  
  tasks:
    - name: INSTALL PACKAGES
      include_tasks: tasks/install_packages.yml
    - name: INSTALL PRINT-SERVER
      include_tasks: tasks/install_print-server.yml
    - name: TAILSCALE
      include_tasks: tasks/install_and_setup_tailscale.yml
    - name: ADD HOST TO DNS SERVER
      include_tasks: tasks/add_hostname_to_pihole_dns.yml