- name: PROVISION GOTIFY LXC
  hosts: gotify
  become: yes
  
  pre_tasks:
    - name: TAILSCALE
      include_tasks: tasks/install_and_setup_tailscale.yml
    - name: UPDATE SYSTEM
      include_tasks: tasks/update_system.yml
  
  tasks:
    
