- name: PROVISION MEALIE LXC
  hosts: mealie
  become: true

  pre_tasks:
    - name: UPDATE SYSTEM
      include_tasks: tasks/update_system.yml
  
  tasks:
    # - name: SSH KEYS
    #   include_tasks: tasks/ssh_keys.yml
    - name: SET TIMEZONE
      include_tasks: tasks/set_timezone.yml
    - name: TAILSCALE
      include_tasks: tasks/install_and_setup_tailscale.yml