- name: PROVISION LOCAL CADDY
  hosts: local-caddy
  become: yes
  
  # pre_tasks:
  #   - name: ADD HOSTS TO DNS SERVER
  #     include_tasks: tasks/add_hosts_to_pihole_dns.yml
  #   - name: BOOTSTRAP NEW HOST
  #     include_tasks: tasks/bootstrap_new_host.yml
  #     when: bootstrap is defined and bootstrap|bool is true
  #     vars:
  #       - ansible_user: "{{ primary_user }}"
  #       - ansible_host: "{{ ip }}"
  
  tasks:
    - name: UPDATE SYSTEM
      include_tasks: tasks/update_system.yml
    - name: INSTALL PACKAGES
      include_tasks: tasks/install_packages.yml
    - name: INSTALL CONFIGURE CADDY
      include_tasks: tasks/install_config_caddy.yml
      vars:
        - caddy_file: "local_Caddyfile.j2"
    - name: TAILSCALE
      include_tasks: tasks/install_and_setup_tailscale.yml