- name: PROVISION NEXTCLOUD
  hosts: nextcloud
  become: true
  # vars:
  #   ansible_user: "{{ primary_user }}"
  
  tasks:
    - name: TAILSCALE
      include_tasks: tasks/install_and_setup_tailscale.yml
    - name: MOUNT DRIVE NFS
      include_tasks: tasks/mount_drive_nfs.yml