# $ ansible-playbook playbooks/provision_audiobookshelf_lxc.yml

- name: PROVISION AUDIOBOOKSHELF LXC
  hosts: audiobookshelf
  become: yes
  
  pre_tasks:
    - name: TAILSCALE
      include_tasks: tasks/install_and_setup_tailscale.yml
    - name: UPDATE SYSTEM
      include_tasks: tasks/update_system.yml
  
  tasks:
    - name: SET TIMEZONE
      include_tasks: tasks/set_timezone.yml
    - name: MOUNT MEDIA NFS
      include_tasks: tasks/mount_media_nfs.yml