- name: PROVISION LOCAL CADDY
  hosts: caddy-local
  become: yes
  
  tasks:
    - name: UPDATE SYSTEM
      include_tasks: tasks/update_system.yml
    - name: INSTALL PACKAGES
      include_tasks: tasks/install_packages.yml
    - name: INSTALL CONFIGURE CADDY
      include_tasks: tasks/install_config_caddy.yml
      vars:
        caddy_file: "local_Caddyfile.j2"
      tags: config
    - name: TAILSCALE
      include_tasks: tasks/install_and_setup_tailscale.yml

