- name: PROVISION ANYTYPE LXC
  hosts: anytype
  become: yes
  
  pre_tasks:
    - name: UPDATE SYSTEM
      include_tasks: tasks/update_system.yml
  
  tasks:
    # - name: SSH KEYS
    #   include_tasks: tasks/ssh_keys.yml
    - name: TAILSCALE
      include_tasks: tasks/install_and_setup_tailscale.yml
