# $ ansible-playbook playbooks/provision_uptimekuma_lxc.yml

- name: PROVISION UPTIMEKUMA LXC
  hosts: uptimekuma
  become: yes
  
  pre_tasks:
    - name: UPDATE SYSTEM
      include_tasks: tasks/update_system.yml
  
  tasks:
    - name: TAILSCALE
      include_tasks: tasks/install_and_setup_tailscale.yml
    # - name: HELPER SCRIPTS UPDATE
    #   include_tasks: tasks/helper_scripts_update.yml
