- name: PROVISION DIGITAL OCEAN CADDY
  hosts: rn-pangolin
  become: yes
  
  tasks:
    - name: TAILSCALE
      include_tasks: tasks/install_and_setup_tailscale.yml
    - name: UPDATE SYSTEM
      include_tasks: tasks/update_system.yml
