- name: PROVISION LINKWARDEN LXC
  hosts: linkwarden
  become: yes
  
  pre_tasks:
    - name: UPDATE SYSTEM
      include_tasks: tasks/update_system.yml
  
  tasks:
    - name: TAILSCALE
      include_tasks: tasks/install_and_setup_tailscale.yml
