- hosts: servers
  become: yes
  tasks:
    - name: install samba
      apt:
        name:
          - samba
          - samba-common-bin
        state: present
        update_cache: true
      become: true