- hosts: servers
  become: yes
  tasks:
    - name: install samba
      apt:
        name:
          - samba
          - samba-common-bin
        state: present
        update_cache: true
      become: true
    
    - name: add docker repository to apt
      apt_repository:
        filename: docker 
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: install docker engine
      apt:
        name: 
          - docker-ce 
          - docker-ce-cli 
          - containerd.io
        state: present
        update_cache: true
      become: true

    - name: test docker
      command: docker info
      become: true