# $ ansible-playbook playbooks/provision_plex_lxc.yml

- name: PROVISION PLEX LXC
  hosts: plex
  become: yes
  
  pre_tasks:
    - name: UPDATE SYSTEM
      include_tasks: tasks/update_system.yml
  
  tasks:
    - name: SSH KEYS
      include_tasks: tasks/ssh_keys.yml
    - name: SET TIMEZONE
      include_tasks: tasks/set_timezone.yml
    - name: MOUNT MEDIA NFS
      include_tasks: tasks/mount_media_nfs.yml
    - name: MOUNT HOME MEDIA NFS
      include_tasks: tasks/mount_home_media_nfs.yml
    - name: TAILSCALE
      include_tasks: tasks/install_and_setup_tailscale.yml