# $ ansible-playbook playbooks/provision_pbs.yml

# After successfully running this playbook, need to add qdevice on proxmox cluster node by running this on the cluster node:
# pvecm qdevice setup 192.168.86.112 -f

- name: PROVISION PROXMOX BACKUP SERVER and QDEVICE
  hosts: pbs
  become: yes
  
  pre_tasks:
    - name: UPDATE SYSTEM
      include_tasks: tasks/update_system.yml
  
  tasks:
    - name: SSH KEYS
      include_tasks: tasks/ssh_keys.yml
    - name: INSTALL PACKAGES
      include_tasks: tasks/install_packages.yml
    - name: INSTALL DOCKER
      include_tasks: tasks/install_docker.yml
    - name: SETUP QDEVICE
      include_tasks: tasks/setup_qdevice.yml
    - name: SETUP SAMBDA SHARES
      include_tasks: tasks/samba_shares.yml
    - name: MOUNT BACKUPS SMB SHARE
      include_tasks: tasks/mount_backups_smb.yml
    - name: MOUNT MEDIA SMB SHARE
      include_tasks: tasks/mount_media_smb.yml
    - name: SETUP REMOTE BACKUPS
      include_tasks: tasks/setup_backups.yml
    - name: TAILSCALE
      include_tasks: tasks/install_and_setup_tailscale.yml