# $ ansible-playbook playbooks/provision_homarr.yml

- name: PROVISION HOMARR
  hosts: homarr
  become: yes
  
  pre_tasks:
    - name: UPDATE SYSTEM
      include_tasks: tasks/update_system.yml
  
  tasks:
    - name: SSH KEYS
      include_tasks: tasks/ssh_keys.yml
    - name: SET TIMEZONE
      include_tasks: tasks/set_timezone.yml
    - name: SETUP SAMBDA SHARES
      include_tasks: tasks/samba_shares.yml
    - name: TAILSCALE
      include_tasks: tasks/install_and_setup_tailscale.yml
    - name: UPDATE DOCKER
      include_tasks: tasks/update_docker.yml
      when: update_docker is defined and update_docker|bool is true