# $ ansible-playbook playbooks/provision_starlord.yml

- name: PROVISION STARLORD
  hosts: starlord
  become: yes
  tasks:
    - name: SSH KEYS
      include_tasks: tasks/ssh_keys.yml
    - name: UPDATE SYSTEM
      include_tasks: tasks/update_system.yml
    - name: TAILSCALE
      include_tasks: tasks/install_and_setup_tailscale.yml