# $ ansible-playbook ./playbooks/provision_server-dev.yml -i ./inventory/hosts.yml

- name: PROVISION SERVER05
  hosts: server-dev
  become: yes
  tasks:
    - name: SSH KEYS
      include_tasks: "./tasks/ssh_keys.yml"
    - name: SET TIMEZONE
      include_tasks: "./tasks/set_timezone.yml"
    - name: UPDATE SYSTEM
      include_tasks: "./tasks/update_system.yml"
    - name: INSTALL PACKAGES
      include_tasks: "./tasks/install_packages.yml"
    - name: INSTALL DOCKER
      include_tasks: "./tasks/install_docker.yml"
    - name: SETUP SAMBDA SHARES
      include_tasks: "./tasks/samba_shares.yml"
    # - name: DOCKER DOWN
      # include_tasks: "./tasks/docker_down.yml"
    # - name: RESTORE FILES FROM BACKUP
      # include_tasks: "./tasks/restore_backups.yml"
    # - name: DOCKER PULL AND UP
      # include_tasks: "./tasks/update_docker.yml"