# $ ansible-playbook playbooks/provision_jellyfin_lxc.yml

- name: PROVISION JELLYFIN LXC
  hosts: jellyfin
  become: yes
  
  pre_tasks:
    - name: UPDATE SYSTEM
      include_tasks: tasks/update_system.yml
  
  tasks:
    - name: SSH KEYS
      include_tasks: tasks/ssh_keys.yml
    - name: SET TIMEZONE
      include_tasks: tasks/set_timezone.yml
    - name: MOUNT MEDIA NFS
      include_tasks: tasks/mount_media_nfs.yml
    - name: LXC GPU PASSTHROUGH
      include_tasks: tasks/lxc_gpu_passthrough.yml
    # - name: TAILSCALE
      # include_tasks: tasks/install_and_setup_tailscale.yml