# $ ansible-playbook ./playbooks/provision_ansible_control.yml -i ./inventory/hosts.yml

- name: PROVISION SERVER02
  hosts: new_control_node
  become: yes
  vars:
    - ansible_host_key_checking: false
  tasks:
    - name: SSH KEYS
      include_tasks: "./tasks/ssh_keys.yml"
    - name: UPDATE SYSTEM
      include_tasks: "./tasks/update_system.yml"
    - name: INSTALL PACKAGES
      include_tasks: "./tasks/install_packages.yml"
    - name: INSTALL DOCKER
      include_tasks: "./tasks/install_docker.yml"
    - name: SETUP SAMBDA SHARES
      include_tasks: "./tasks/samba_shares.yml"