# $ ansible-playbook playbooks/provision_cluster_nodes.yml

- name: PROVISION STARLORD
  hosts: stark, starlord
  become: yes
  tasks:
    - name: SSH KEYS
      include_tasks: tasks/ssh_keys.yml
    - name: UPDATE SYSTEM
      include_tasks: tasks/update_system.yml
    - name: INSTALL PACKAGES
      include_tasks: tasks/install_packages.yml
    - name: SETUP PROXMOX NOTIFICATIONS
      include_tasks: tasks/setup_proxmox_ve_notifications.yml
      when: inventory_hostname == "stark"
    - name: TAILSCALE
      include_tasks: tasks/install_and_setup_tailscale.yml
      
#- name: PROVISION STARK
#  hosts: stark
#  become: yes
#  tasks:
#    - name: SSH KEYS
#      include_tasks: tasks/ssh_keys.yml
#    - name: UPDATE SYSTEM
#      include_tasks: tasks/update_system.yml
#    - name: SETUP PROXMOX NOTIFICATIONS
#      include_tasks: tasks/setup_proxmox_ve_notifications.yml
#    - name: TAILSCALE
#      include_tasks: tasks/install_and_setup_tailscale.yml