# $ ansible-playbook ./playbooks/restore_backups.yml -i ./inventory/hosts.yml

- hosts: server01
  become: yes
  tasks:
    - name: Synchronize two directories on one remote host.
      ansible.posix.synchronize:
        src: "/mnt/external/backups/latest/{{ inventory_hostname }}/opt/"
        dest: /opt/
      delegate_to: "{{ inventory_hostname }}"
