# $ ansible-playbook ./playbooks/restore_backups.yml -i ./inventory/hosts.yml -e "hosts=HOST"

- hosts: "{{ hosts }}"
  become: yes
  tasks:
    - name: Restore opt folder to host
      ansible.posix.synchronize:
        src: "/mnt/external/backups/latest/{{ inventory_hostname }}/opt/"
        dest: /opt/
        delete: yes
      delegate_to: "{{ inventory_hostname }}"
