# $ ansible-playbook playbooks/run_tasks.yml -e "hosts=HOST tasks=TASKS"

- name: "RUN TASKS: {{ tasks }}"
  hosts: "{{ hosts }}"
  become: yes
  tasks:
    - include_tasks: "tasks/{{ tasks }}.yml"