# $ ansible-playbook ./playbooks/run_tasks.yml -i ./inventory/hosts.yml -e "hosts=HOST tasks=TASKS"

- hosts: "{{ hosts }}"
  vars:
    - ansible_host_key_checking: false
  become: yes
  tasks:
    - include_tasks: "./tasks/{{ tasks }}.yml"