# $ ansible-playbook playbooks/run_tasks.yml -e "hosts=HOST tasks=TASKS"

- name: "RUN TASKS: {{ tasks }}"
  hosts: "{{ hosts }}"
  become: yes
  tasks:
    - name: Ansible User
      ansible.builtin.debug:
        msg: "{{ ansible_user_id }}"
    
    - include_tasks: "tasks/{{ tasks }}.yml"