# $ ansible-playbook ./playbooks/setup_server01.yml -i ./inventory/hosts.yml

- name: SETUP SERVER01
  hosts: server01
  become: yes
  tasks:
    - name: SSH KEYS
      include_tasks: "./tasks/ssh_keys.yml"
    - name: SET TIMEZONE
      include_tasks: "./tasks/set_timezone.yml"
    - name: UPDATE SYSTEM
      include_tasks: "./tasks/update_system.yml"
    - name: MOUNT EXTERNAL DRIVE
      include_tasks: "./tasks/mount_external_drive.yml"
    - name: INSTALL PACKAGES
      include_tasks: "./tasks/install_packages.yml"
    - name: INSTALL DOCKER
      include_tasks: "./tasks/install_docker.yml"
    - name: SETUP SAMBDA SHARES
      include_tasks: "./tasks/samba_shares.yml"
    - name: DOCKER DOWN
      include_tasks: "./tasks/docker_down.yml"
    - name: RESTORE FILES FROM BACKUP
      include_tasks: "./tasks/restore_backups.yml"
    - name: SETUP SERVER TO PERFORM DAILY BACKUPS
      include_tasks: "./tasks/setup_backups.yml"
    - name: DOCKER PULL AND UP
      include_tasks: "./tasks/update_docker.yml"