# $ ansible-playbook ./playbooks/ssh_keys.yml -i ./inventory/hosts.yml -e "hosts=HOST"

- hosts: localhost
  tasks:
    - name: generate SSH key from localhost
      openssh_keypair:
        path: "~/.ssh/id_rsa"
        type: rsa
        size: 2048
        state: present
        force: no
    
    - name: copy other ssh keys to localhost
      ansible.posix.authorized_key:
        user: patrick
        state: present
        key: '{{ item }}'
      with_file:
        - ../public_keys/hp_laptop_id_rsa.pub
        
- hosts: "{{ hosts }}"
  become: yes
  tasks:
    - name: copy localhost ssh key to hosts
      ansible.posix.authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ lookup('file', '/home/patrick/.ssh/id_rsa.pub') }}"
    
    - name: Create a 2048-bit SSH key for user
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        generate_ssh_key: yes
        ssh_key_bits: 2048
    
    - name: Fetch the keyfile from one server to another
      become_user: "{{ ansible_user }}"
      ansible.builtin.fetch: 
        src: "~/.ssh/id_rsa.pub"
        dest: "buffer/{{inventory_hostname}}-id_rsa.pub"
        flat: yes
    
    - name: Copy the key add to authorized_keys using Ansible module
      ansible.posix.authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ lookup('file','buffer/{{item}}-id_rsa.pub')}}"
      when: item != inventory_hostname
      with_items: 
        - "{{ groups[hosts] }}"
        
    - name: copy other ssh keys to hosts
      ansible.posix.authorized_key:
        user: pi
        state: present
        key: '{{ item }}'
      with_file:
        - ../public_keys/homeassistant_id_rsa.pub
        - ../public_keys/hp_laptop_id_rsa.pub
        - ../public_keys/phone_id_rsa.pub
