# $ ansible-playbook ./playbooks/ssh_keys.yml -i ./inventory/hosts.yml -e "hosts=HOST"

- hosts: localhost
  tasks:
    - name: generate SSH key 
      openssh_keypair:
        path: "~/.ssh/id_rsa"
        type: rsa
        size: 2048
        state: present
        force: no

- hosts: "{{ hosts }}"
  tasks:
    - name: Set authorized key taken from file
      ansible.posix.authorized_key:
        user: pi
        state: present
        key: "{{ lookup('file', '/home/patrick/.ssh/id_rsa.pub') }}"