# $ ansible-playbook ./playbooks/ssh_keys.yml -i ./inventory/hosts.yml -e "hosts=HOST"

- hosts: localhost
  tasks:
    - name: generate SSH key from localhost
      openssh_keypair:
        path: "~/.ssh/id_rsa"
        type: rsa
        size: 2048
        state: present
        force: no
    
    - name: copy other ssh keys to localhost
      ansible.posix.authorized_key:
        user: patrick
        state: present
        key: '{{ item }}'
      with_file:
        - ../public_keys/hp_laptop_id_rsa.pub
        
- hosts: "{{ hosts }}"
  tasks:
    - name: copy localhost ssh key to hosts
      ansible.posix.authorized_key:
        user: pi
        state: present
        key: "{{ lookup('file', '/home/patrick/.ssh/id_rsa.pub') }}"
        
    - name: copy other ssh keys to hosts
      ansible.posix.authorized_key:
        user: pi
        state: present
        key: '{{ item }}'
      with_file:
        - ../public_keys/homeassistant_id_rsa.pub
        - ../public_keys/hp_laptop_id_rsa.pub
        - ../public_keys/phone_id_rsa.pub
