# $ ansible-playbook ./playbooks/test_playbook.yml -i ./inventory/hosts.yml

- hosts: server01
  become: yes
  tasks:
    - name: Test jinja2template
      template: src=backups.sh.js dest=/opt/backups.sh