# $ ansible-playbook ./playbooks/updates.yml -i ./inventory/hosts.yml -e "hosts=HOST"

- hosts: "{{ hosts }}"
  become: yes
  tasks:
    - name: apt
      apt:
        update_cache: yes
        upgrade: 'yes'
    
    - name: docker compose pull
      ansible.builtin.shell:
        cmd: docker compose pull
        chdir: "{{ item }}"
      loop: "{{ docker_compose_dirs }}"
        
    - name: docker compose up -d
      ansible.builtin.shell:
        cmd: docker compose up -d
        chdir: "{{ item }}"
      loop: "{{ docker_compose_dirs }}"