# $ ansible-playbook ./playbooks/updates.yml -i ./inventory/hosts.yml -e "hosts=HOST"

- hosts: "{{ hosts }}"
  become: yes
  tasks:
    - name: apt
      apt:
        update_cache: yes
        upgrade: 'yes'