# $ ansible-playbook ./playbooks/update_servers.yml -e "hosts=HOST"

- hosts: "{{ hosts }}"
  become: yes
  tasks:
    - name: UPDATE SYSTEM
      include_tasks: tasks/update_system.yml
    - name: UPDATE DOCKER CONTAINERS
      include_tasks: tasks/update_docker.yml
      when: docker_compose_dirs is defined
      